# Generated by Django 5.1.3 on 2024-11-15 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название товара')),
                ('article', models.CharField(max_length=255, verbose_name='Артикул')),
                ('brand', models.CharField(max_length=255, verbose_name='Бренд-производитель')),
                ('description', models.TextField(verbose_name='Описание товара')),
                ('rating', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='Оценка товара')),
                ('quantity', models.IntegerField(verbose_name='Количество товара на складе')),
            ],
        ),
    ]
